// Simmetric Chat — Copyright (C) 2026 Simmetric Chat
// SPDX-License-Identifier: AGPL-3.0-or-later
// This file is part of the Simmetric Chat community build.
// See LICENSE and NOTICE at the repository root for full terms.

/**
 * RUNBOOK (Phase 205-04, OCR-05 / D-13/D-14) — how to actually run this
 * suite locally:
 *
 *   # Skip branch (no daemon needed — must exit 0 via describe.skip):
 *   OLLAMA_BASE_URL= pnpm --filter server exec jest \
 *     --config jest.config.integration-nodb.js \
 *     --cacheDirectory .jest-cache/server-nodb \
 *     -- src/__tests__/ocrReliability.integration.test.ts
 *
 *   # Gated run (real daemon + pulled model — runs the pre/post comparison):
 *   OLLAMA_BASE_URL=http://localhost:11434 pnpm --filter server exec jest \
 *     --config jest.config.integration-nodb.js \
 *     --cacheDirectory .jest-cache/server-nodb \
 *     -- src/__tests__/ocrReliability.integration.test.ts
 *
 * - The integration-nodb config declares NO cacheDirectory of its own — the
 *   /tmp default fails in some environments, so the flag is REQUIRED on
 *   every invocation (do not drop it).
 * - No Postgres is needed: this suite needs only the ollama daemon, the
 *   committed fixtures and `helpers/setupEnv` (loaded as a setupFile by the
 *   nodb config; imported again here so the file is config-agnostic).
 * - The `OLLAMA_BASE_URL` skip-guard below (the `ollamaAvailable` const) is
 *   the correct no-model behavior: with the env var absent the suite skips
 *   — do NOT "fix" the `env.ts` OLLAMA_BASE_URL default
 *   (`http://ollama:11434`): it is compose-shaped by design and dead-DNS
 *   only for host-side processes, so pass the override at the command line.
 * - The model arm requires the model to be PULLED on the targeted instance
 *   (`ollama pull glm-ocr:latest`); the per-model availability probe below
 *   (`client.list()`) skips the fixture tests with an explicit reason when
 *   it is absent — never a fake fail, never a silent skip (204 D-05
 *   precedent). Operator opt-in: set `OCR_MODEL` to target another model
 *   (e.g. `glm-ocr-optimized:latest`) — the default stays `glm-ocr:latest`
 *   (Phase 205 D-12).
 * - Timeouts: vision is slow — PER_ARM_TIMEOUT_MS (300s) bounds one OCR
 *   call; each fixture test runs BOTH arms so its jest timeout is
 *   2 × arm + probe slack.
 *
 * What the suite does (per fixture, in the fixed order straight →
 * rotated-5deg → table → small-text):
 *  1. PRE arm  — jest-mocked `preprocessForOcr` passthrough (applied=false):
 *     the original fixture bytes reach `ocrPage` unmodified. The ONLY delta
 *     between the arms is preprocessing enabled vs disabled (OCR-05
 *     adjacency invariant — same fixture bytes, same model, same options).
 *  2. POST arm — the real 205-03 preprocessing chain runs (grayscale →
 *     resize ≤1024 → projection-profile deskew → JPEG q85). Before
 *     comparing markdown, the suite asserts the hook REALLY applied
 *     (`applied === true` for straight/rotated/table — suite-level ordering
 *     probe; small-text is exempt only if the estimator legitimately skips
 *     rotation, which the row records).
 *  3. Classify per Pitfall 8: clean (truncated falsy + non-empty),
 *     salvaged (truncated=true — the 260829-lkq done-less-stream rule
 *     counts as a DEGRADED SUCCESS, not a failure), failed (empty markdown
 *     or thrown).
 *  4. On the gated run, write the measured rows into the marker-delimited
 *     block in docs/OCR_RELIABILITY.md (idempotent replace). In CI the doc
 *     stays as-committed — never hand-write numbers there.
 */

import "./helpers/setupEnv";
import fs from "fs";
import path from "path";
import { ocrPage, type OcrPageResult } from "../ocr/ollamaVisionClient";
import { resolveModelConfig } from "../ocr/modelRegistry";
import { getOllamaClient } from "../services/ollamaClient";

const ollamaAvailable = !!process.env.OLLAMA_BASE_URL;

const TIMEOUT_MS = 660000; // both arms + probe slack (see RUNBOOK)
const PROBE_TIMEOUT_MS = 30000;
const PAGE_NUMBER = 1;
const TOTAL_PAGES = 1;

// Model under test — OCR_MODEL default posture (Phase 205 D-12: the default
// stays glm-ocr:latest; other names are a documented operator opt-in).
const MODEL_NAME = process.env.OCR_MODEL || "glm-ocr:latest";

const REPO_ROOT = path.resolve(__dirname, "..", "..", "..", "..");
const DOC_PATH = path.join(REPO_ROOT, "docs", "OCR_RELIABILITY.md");
const BLOCK_BEGIN =
  "<!-- regression:begin (auto-generated by the OLLAMA_BASE_URL-gated run of packages/server/src/__tests__/ocrReliability.integration.test.ts — do not hand-edit rows) -->";
const BLOCK_END = "<!-- regression:end -->";

// ---------------------------------------------------------------------------
// Committed fixtures (Pitfall 7: binaries are the determinism guarantee —
// the suite READS committed files, never generates at runtime).
// ---------------------------------------------------------------------------

const FIXTURES_DIR = path.join(
  REPO_ROOT,
  "packages",
  "server",
  "src",
  "ocr",
  "__tests__",
  "fixtures",
  "regression",
);

/**
 * Known-content constants — MUST stay in sync with the header contract in
 * scripts/generate-ocr-regression-fixtures.cjs (the generator carries the
 * mirrored literals; these are the transcription-assertion targets).
 */
const KNOWN_CONTENT = {
  straight: {
    title: "OCR Regression Fixture: Straight Page",
    bodyLine: "Deterministic sampling keeps repeated measurement runs comparable.",
    fixture: "straight.png",
    note: "normal A4-proportioned multi-line text page",
    requireApplied: true,
  },
  "rotated-5deg": {
    title: "OCR Regression Fixture: Straight Page",
    bodyLine: "Preprocessing restores skewed pages without thresholding the output.",
    fixture: "rotated-5deg.png",
    note: "same page content pre-rotated ~5° (deskew stress case)",
    requireApplied: true,
  },
  table: {
    title: "OCR Regression Fixture: Table Page",
    bodyLine: "first data row",
    fixture: "table.png",
    note: "bordered grid of known cells (pipe-restore-able)",
    requireApplied: true,
  },
  "small-text": {
    title: "OCR Regression Fixture: Straight Page",
    bodyLine: "The quick brown fox jumps over the lazy dog near the riverbank.",
    fixture: "small-text.png",
    note: "same body content at ~half the point size (render-scale/preprocessing stress case)",
    // The ≤1024 downscale may legitimately not apply / rotation may skip on
    // the small page — the row RECORDS applied state instead of asserting it.
    requireApplied: false,
  },
} as const;

type FixtureId = keyof typeof KNOWN_CONTENT;
const FIXTURE_ORDER: FixtureId[] = ["straight", "rotated-5deg", "table", "small-text"];

// ---------------------------------------------------------------------------
// Preprocessing mock seam — the ONLY delta between the two arms.
// ---------------------------------------------------------------------------

interface MockPreprocessResult {
  buffer: Buffer;
  applied: boolean;
  estimatedSkewDeg: number;
  resized: boolean;
}

// jest.mock hoists this factory above the imports — everything it touches
// lives INSIDE the factory (TDZ-safe under @swc/jest, ollamaVisionClient
// test convention). Default (no handler queued) = the REAL chain, i.e. the
// production behavior; each arm pushes exactly ONE handler that ocrPage's
// single preprocessForOcr call consumes.
jest.mock("../ocr/preprocessing", () => {
  const actual = jest.requireActual("../ocr/preprocessing") as {
    preprocessForOcr: (input: Buffer) => Promise<MockPreprocessResult>;
  };
  type Handler = (input: Buffer) => Promise<MockPreprocessResult>;
  const handlers: Handler[] = [];
  const preprocessForOcr = (input: Buffer): Promise<MockPreprocessResult> => {
    const handler = handlers.shift();
    return handler ? handler(input) : actual.preprocessForOcr(input);
  };
  return {
    preprocessForOcr,
    __handlers: handlers,
    __realPreprocessForOcr: actual.preprocessForOcr,
  };
});

const preprocessMock = require("../ocr/preprocessing") as {
  __handlers: Array<(input: Buffer) => Promise<MockPreprocessResult>>;
  __realPreprocessForOcr: (input: Buffer) => Promise<MockPreprocessResult>;
};

interface RecordedHook {
  applied?: boolean;
  estimatedSkewDeg?: number;
  resized?: boolean;
  inputBytes?: number;
  outputBytes?: number;
}

function queuePassthroughArm(): void {
  // PRE arm: original bytes flow through untouched (applied=false).
  preprocessMock.__handlers.push(async (input) => ({
    buffer: input,
    applied: false,
    estimatedSkewDeg: 0,
    resized: false,
  }));
}

function queueRealArm(record: RecordedHook): void {
  // POST arm: the real 205-03 chain, with the PreprocessResult recorded so
  // the suite-level ordering probe (applied === true) can be asserted.
  preprocessMock.__handlers.push(async (input) => {
    const real = await preprocessMock.__realPreprocessForOcr(input);
    record.applied = real.applied;
    record.estimatedSkewDeg = real.estimatedSkewDeg;
    record.resized = real.resized;
    record.inputBytes = input.length;
    record.outputBytes = real.buffer.length;
    return real;
  });
}

// ---------------------------------------------------------------------------
// Measurement + classification (Pitfall 8 — three classes, salvage = degraded
// success, never a failure).
// ---------------------------------------------------------------------------

type OcrClass = "clean" | "salvaged" | "failed";

interface ArmRow {
  arm: "pre" | "post";
  ok: boolean;
  error?: string;
  durationMs: number; // -1 when the arm failed
  tokensUsed: number; // -1 when the arm failed
  ttftMs: number; // -1 when the arm failed
  className: OcrClass;
  chars: number; // transcription length (0 when failed/empty)
  markdown: string; // full transcription (similarity source; "" when failed)
  payloadBytes: number; // bytes the arm sent to the model (post: processed buffer)
  hook?: RecordedHook;
}

function classifyResult(result: OcrPageResult): OcrClass {
  const markdown = result.markdown ?? "";
  if (markdown.trim().length === 0) return "failed"; // empty transcription = failed class (OCR-05 empty probe)
  return result.truncated ? "salvaged" : "clean";
}

function rowFromResult(
  arm: "pre" | "post",
  result: OcrPageResult,
  payloadBytes: number,
  hook?: RecordedHook,
): ArmRow {
  const markdown = result.markdown ?? "";
  return {
    arm,
    ok: true,
    durationMs: result.durationMs,
    tokensUsed: result.tokensUsed,
    ttftMs: result.ttftMs ?? -1,
    className: classifyResult(result),
    chars: markdown.length,
    markdown,
    payloadBytes,
    hook,
  };
}

function failedRow(arm: "pre" | "post", error: string): ArmRow {
  return {
    arm,
    ok: false,
    error,
    durationMs: -1,
    tokensUsed: -1,
    ttftMs: -1,
    className: "failed",
    chars: 0,
    markdown: "",
    payloadBytes: -1,
  };
}

/** Token-level Jaccard similarity over lowercase alphanumeric words. */
function contentSimilarity(a: string, b: string): number {
  const tokenize = (s: string): Set<string> =>
    new Set((s.toLowerCase().match(/[a-z0-9]+/g) ?? []));
  const ta = tokenize(a);
  const tb = tokenize(b);
  if (ta.size === 0 && tb.size === 0) return 1;
  let inter = 0;
  for (const t of ta) if (tb.has(t)) inter += 1;
  const union = ta.size + tb.size - inter;
  return union === 0 ? 0 : inter / union;
}

interface FixtureMeasurement {
  pre?: ArmRow;
  post?: ArmRow;
  similarity?: number;
}

const MEASUREMENTS = new Map<FixtureId, FixtureMeasurement>();

// ---------------------------------------------------------------------------
// Doc block write (marker-delimited, idempotent replace — gated runs only;
// the describe body never executes writes in the skip branch).
// ---------------------------------------------------------------------------

function readDoc(): string | null {
  try {
    return fs.readFileSync(DOC_PATH, "utf-8");
  } catch {
    return null;
  }
}

function writeRegressionBlock(blockContent: string): void {
  const doc = readDoc();
  if (!doc) {
    console.warn(
      "[ocrReliability] docs/OCR_RELIABILITY.md not found — rows kept in stdout only",
    );
    return;
  }
  const block = `${BLOCK_BEGIN}\n${blockContent}\n${BLOCK_END}`;
  let updated: string;
  if (doc.includes(BLOCK_BEGIN) && doc.includes(BLOCK_END)) {
    const start = doc.indexOf(BLOCK_BEGIN);
    const end = doc.indexOf(BLOCK_END) + BLOCK_END.length;
    updated = doc.slice(0, start) + block + doc.slice(end);
  } else {
    const sep = doc.endsWith("\n") ? "" : "\n";
    updated = `${doc}${sep}\n${block}\n`;
  }
  fs.writeFileSync(DOC_PATH, updated);
  console.log("[ocrReliability] regression rows written to docs/OCR_RELIABILITY.md");
}

/**
 * Known-content verification (log-level, never an assert — transcription
 * wording legitimately varies across model revisions). Counts how many of
 * the fixture's known strings appear (case-insensitive) in the
 * transcription. A miss is worth an operator's attention, not a red build.
 */
function knownContentHits(id: FixtureId, markdown: string): number {
  const meta = KNOWN_CONTENT[id];
  const hay = markdown.toLowerCase();
  const needles = [meta.title, meta.bodyLine];
  return needles.filter((s) => hay.includes(s.toLowerCase())).length;
}

function formatRow(id: FixtureId, meta: (typeof KNOWN_CONTENT)[FixtureId], row: ArmRow): string {
  const hookNote =
    row.hook && row.hook.applied !== undefined
      ? `applied=${row.hook.applied}, skew=${row.hook.estimatedSkewDeg ?? 0}°, in=${row.hook.inputBytes ?? "?"}B, out=${row.hook.outputBytes ?? "?"}B`
      : "passthrough (applied=false)";
  const hits = `${knownContentHits(id, row.markdown)}/2`;
  const errorNote = row.error ? ` ERROR: ${row.error}` : "";
  return `| ${id} | ${row.arm === "pre" ? "pre (no preprocessing)" : "post (preprocessing)"} | ${row.durationMs} | ${row.tokensUsed} | ${row.ttftMs} | ${row.className} | ${row.chars} | ${meta.note}; ${hookNote}; known-content=${hits}${errorNote} |`;
}

function buildBlockContent(): string {
  const meta = KNOWN_CONTENT;
  const lines: string[] = [
    `**Post-fix regression** — captured by the OLLAMA_BASE_URL-gated suite`,
    `\`packages/server/src/__tests__/ocrReliability.integration.test.ts\` at ${new Date().toISOString()}.`,
    `Posture: model \`${MODEL_NAME}\` (registry num_ctx ${
      resolveModelConfig(MODEL_NAME).contextWindow
    }), chat endpoint, options { temperature 0, num_predict from OCR_NUM_PREDICT, top_k 1 }, preprocessing (205-03) in the POST arm only — the PRE arm jest-passes the original fixture bytes through (the ONLY delta between arms).`,
    ``,
    `| Fixture | Arm | durationMs | tokensUsed | ttftMs | class | chars | note |`,
    `|---------|-----|-----------:|-----------:|-------:|-------|------:|------|`,
  ];
  // Fixed row order: straight → rotated-5deg → table → small-text (OCR-05
  // ordering invariant — stable across runs regardless of execution order).
  for (const id of FIXTURE_ORDER) {
    const m = MEASUREMENTS.get(id);
    if (!m) continue;
    if (m.pre) lines.push(formatRow(id, meta[id], m.pre));
    if (m.post) lines.push(formatRow(id, meta[id], m.post));
    if (m.pre && m.post && m.pre.ok && m.post.ok) {
      lines.push(
        `| ${id} | delta (post − pre) | ${m.post.durationMs - m.pre.durationMs} | ${m.post.tokensUsed - m.pre.tokensUsed} | ${m.post.ttftMs - m.pre.ttftMs} | ${m.post.className} vs ${m.pre.className} | ${m.post.chars - m.pre.chars} | token similarity pre↔post = ${m.similarity?.toFixed(3) ?? "n/a"} |`,
      );
    }
  }
  lines.push(``);
  lines.push(
    `Classes per salvage accounting §4: clean = done-marker stream + non-empty markdown; salvaged = truncated=true (260829-lkq done-less stream — DEGRADED SUCCESS, not a failure; the rule applies to both glm-ocr and glm-ocr-optimized); failed = empty markdown or thrown. Environment: Ollama daemon at \`${process.env.OLLAMA_BASE_URL}\` — daemon/model/CPU details in §6.`,
  );
  return lines.join("\n");
}

function persistRowsIfMeasured(): void {
  if (MEASUREMENTS.size === 0) return;
  writeRegressionBlock(buildBlockContent());
}

// ---------------------------------------------------------------------------
// The gated suite.
// ---------------------------------------------------------------------------

(ollamaAvailable ? describe : describe.skip)(
  "ocrReliability — glm-ocr regression (OLLAMA_BASE_URL-gated, integration-nodb)",
  () => {
    // Suite setup: committed fixtures MUST exist (OCR-05 — a fixture absent
    // from disk fails the setup with a clear message; this check also runs
    // during collection of the skipped branch, which is safe because the
    // fixtures are committed binaries — Pitfall 7).
    const missing = FIXTURE_ORDER.filter(
      (id) => !fs.existsSync(path.join(FIXTURES_DIR, KNOWN_CONTENT[id].fixture)),
    );
    if (missing.length > 0) {
      throw new Error(
        `[ocrReliability] committed regression fixtures missing: ${missing
          .map((id) => KNOWN_CONTENT[id].fixture)
          .join(", ")} under ${FIXTURES_DIR} — regenerate with \`node scripts/generate-ocr-regression-fixtures.cjs\` and COMMIT the binaries (Pitfall 7).`,
      );
    }

    // Per-model availability probe (nativeToolsIntegration pattern —
    // explicit reason, never silent). client.list() on the same factory.
    const probe = {
      modelAvailable: false as boolean,
      error: null as string | null,
      modelCount: 0,
    };

    beforeAll(async () => {
      const baseUrl = process.env.OLLAMA_BASE_URL as string;
      try {
        const client = getOllamaClient(baseUrl, { timeoutMs: PROBE_TIMEOUT_MS });
        const listed = await client.list();
        const names = (listed.models ?? []).map((m) => (m.name ?? m.model ?? "") as string);
        probe.modelCount = names.length;
        probe.modelAvailable = names.includes(MODEL_NAME);
        if (!probe.modelAvailable) {
          console.warn(
            `[ocrReliability] model ${MODEL_NAME} not present on ${baseUrl} (found ${names.length} models) — fixture tests will be skipped with reason. Pull it with \`ollama pull ${MODEL_NAME}\`.`,
          );
        }
      } catch (err) {
        probe.error = err instanceof Error ? err.message : String(err);
        console.warn(
          `[ocrReliability] could not list models on ${baseUrl} — fixture tests will be skipped with reason: ${probe.error}`,
        );
      }
    }, PROBE_TIMEOUT_MS);

    // Explicit skip-with-reason per fixture test when the model is absent
    // (jasmine `pending` — shows as "marked as pending with reason: …").
    beforeEach(() => {
      if (!probe.modelAvailable) {
        const reason = probe.error
          ? `model availability probe failed on ${String(process.env.OLLAMA_BASE_URL)}: ${probe.error}`
          : `model ${MODEL_NAME} not present on ${String(process.env.OLLAMA_BASE_URL)} — \`ollama pull ${MODEL_NAME}\` first (per-model availability guard, 204 D-05 pattern)`;
        pending(reason);
      }
    });

    const runOcrPage = (buffer: Buffer, modelConfig = resolveModelConfig(MODEL_NAME)) =>
      ocrPage(
        buffer,
        PAGE_NUMBER,
        TOTAL_PAGES,
        MODEL_NAME,
        modelConfig,
        undefined, // signal
        false, // useFallbackPrompt — the standardized glm-ocr prompt path
      );

    for (const id of FIXTURE_ORDER) {
      const meta = KNOWN_CONTENT[id];

      it(
        `fixture ${id} — pre vs post preprocessing (${meta.note})`,
        async () => {
          const fixturePath = path.join(FIXTURES_DIR, meta.fixture);
          const fixtureBytes = fs.readFileSync(fixturePath);

          const measurement: FixtureMeasurement = {};

          // ---- PRE arm: preprocessing disabled (jest passthrough) ----
          queuePassthroughArm();
          try {
            const result = await runOcrPage(fixtureBytes);
            measurement.pre = rowFromResult("pre", result, fixtureBytes.length);
          } catch (err) {
            measurement.pre = failedRow("pre", err instanceof Error ? err.message : String(err));
            console.error(`[ocrReliability] ${id} PRE arm failed: ${measurement.pre.error}`);
          }

          // ---- POST arm: the real 205-03 chain (hook recorded) ----
          const hook: RecordedHook = {};
          queueRealArm(hook);
          try {
            const result = await runOcrPage(fixtureBytes);
            measurement.post = rowFromResult(
              "post",
              result,
              hook.outputBytes ?? -1,
              hook,
            );
          } catch (err) {
            measurement.post = failedRow("post", err instanceof Error ? err.message : String(err));
            console.error(`[ocrReliability] ${id} POST arm failed: ${measurement.post.error}`);
          }

          MEASUREMENTS.set(id, measurement);

          // Suite-level ordering probe (OCR-03 at the suite level): the
          // POST arm MUST have really applied preprocessing before any
          // markdown comparison — a silently-skipped arm corrupts the
          // comparison. small-text records instead of asserts (the chain
          // may legitimately skip rotation on the small page).
          if (meta.requireApplied) {
            expect(hook.applied).toBe(true);
          } else if (hook.applied === false) {
            console.warn(
              `[ocrReliability] ${id}: preprocessing did not apply (applied=false) — recorded honestly in the row.`,
            );
          }

          // Metric capture per arm + comparison summary (stdout = the
          // operator-visible record even before the doc block is written).
          const summarize = (row: ArmRow | undefined, label: string) => {
            if (!row) return;
            if (row.ok) {
              const hits = knownContentHits(id, row.markdown);
              const knownNote = hits < 2 ? ` — known-content ${hits}/2 (transcription drift vs fixture text — review, not a build failure)` : "";
              console.log(
                `[ocrReliability] ${id} ${label}: ${row.durationMs}ms, ${row.tokensUsed} tokens, ttft ${row.ttftMs}ms, class=${row.className}, ${row.chars} chars, payload ${row.payloadBytes}B, known-content ${hits}/2${knownNote}`,
              );
            } else {
              console.log(`[ocrReliability] ${id} ${label}: FAILED — ${row.error}`);
            }
          };
          summarize(measurement.pre, "PRE ");
          summarize(measurement.post, "POST");

          if (measurement.pre?.ok && measurement.post?.ok) {
            const similarity = contentSimilarity(measurement.pre.markdown, measurement.post.markdown);
            measurement.similarity = similarity;
            console.log(`[ocrReliability] ${id} similarity pre↔post: ${similarity.toFixed(3)}`);

            // Payload direction check (log-only warn per plan — RESEARCH
            // probed shrink; a large growth indicates a preprocessing bug).
            // Raw bytes compare 1:1 with the base64 sizes (base64 = ×4/3 on
            // both sides, so the factor is preserved).
            const preBytes = measurement.pre.payloadBytes;
            const postBytes = measurement.post.payloadBytes;
            if (preBytes > 0 && postBytes > preBytes * 2) {
              console.warn(
                `[ocrReliability] ${id}: POST-arm payload (${postBytes}B) exceeds PRE-arm (${preBytes}B) by >2× — pathological growth, preprocessing bug suspected (expected shrink: ≤1024px + JPEG q85).`,
              );
            }

            // Empty-markdown posture is already classified as failed per
            // arm (OCR-05 empty probe: an empty transcription in either arm
            // is recorded as failed for that arm, never dropped from the
            // table) — the rows above carry it.
          }
        },
        TIMEOUT_MS,
      );
    }

    afterAll(() => {
      persistRowsIfMeasured();
    });
  },
);