/**
 * @fileoverview Migration safety audit script (SEED-01). See docs/MIGRATION_SAFETY.md for the policy.
 *
 * Scans every `packages/server/prisma/migrations/<timestamp>_<slug>/migration.sql` and classifies each as
 * `additive` or `destructive` using a strict, finite 4-pattern regex allowlist. Writes two
 * outputs:
 *   - `docs/MIGRATION_AUDIT.md` — human-readable markdown report (committed in git)
 *   - `.migration-audit.json` — machine-readable counter (gitignored, regenerated by every run)
 *
 * Invoked on-demand via `pnpm audit:migrations` (or directly via `tsx scripts/audit-migrations.ts`).
 * Always exits 0 (CI does its own gating — see docs/MIGRATION_SAFETY.md).
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve, sep } from "node:path";
import { logger } from "../src/utils/logger";

/**
 * Destructive operation allowlist (D-02, hardcoded finite list — no heuristics).
 *
 * Each entry is a regex that, when matched against a migration's SQL, classifies the
 * migration as `destructive`. The classification is purely mechanical: if ANY of these
 * patterns matches, the migration is destructive. The 4th pattern's negative lookahead
 * `(?!COLUMN\b)(?!CONSTRAINT\b)(?!DEFAULT\b)(?!INDEX\b)` deliberately whitelists the
 * 3 Prisma idioms (DROP CONSTRAINT, DROP INDEX, ALTER COLUMN ... DROP DEFAULT) that
 * are semantically additive (data is never lost). `COLUMN` is also in the lookahead
 * for explicitness — pattern 2 (DROP COLUMN) catches it first if the column-level
 * form is used, so the COLUMN guard is a defense-in-depth duplicate rather than a
 * standalone matcher.
 */
export const DESTRUCTIVE_PATTERNS: Array<{ name: string; regex: RegExp }> = [
  { name: "DROP TABLE", regex: /^\s*DROP\s+TABLE\b/im },
  { name: "DROP COLUMN", regex: /^\s*ALTER\s+TABLE\s+\S+\s+DROP\s+COLUMN\b/im },
  { name: "TRUNCATE", regex: /^\s*TRUNCATE\b/im },
  {
    name: "ALTER ... DROP (table-level)",
    regex: /^\s*ALTER\s+TABLE\s+\S+\s+DROP\s+(?!COLUMN\b)(?!CONSTRAINT\b)(?!DEFAULT\b)(?!INDEX\b)\S+/im,
  },
  { name: "DELETE", regex: /^\s*DELETE\s+FROM\b/im },
];

export interface MigrationRow {
  /** Migration directory name, e.g. "20260516134634_add_missing_models". */
  slug: string;
  /** Date parsed from the first 8 chars of the slug (YYYY-MM-DD). */
  date: string;
  /** Absolute path to the migration.sql file. */
  path: string;
}

export interface Classification {
  type: "additive" | "destructive";
  operations: string[];
}

/**
 * Classify a migration's SQL content as additive or destructive.
 *
 * Iterates the DESTRUCTIVE_PATTERNS allowlist; a migration is destructive if any pattern
 * matches. Returns the list of matched pattern names (empty for additive).
 */
export function classifyMigration(content: string): Classification {
  const matched = DESTRUCTIVE_PATTERNS
    .filter((p) => p.regex.test(content))
    .map((p) => p.name);
  return {
    type: matched.length > 0 ? "destructive" : "additive",
    operations: matched,
  };
}

const MIGRATIONS_DIR = resolve(dirname(__filename), "..", "prisma", "migrations");
const AUDIT_MD_PATH = resolve(dirname(__filename), "..", "..", "..", "docs", "MIGRATION_AUDIT.md");
const AUDIT_JSON_PATH = resolve(dirname(__filename), "..", "..", "..", ".migration-audit.json");

// Defensive check: AUDIT_MD_PATH / AUDIT_JSON_PATH are resolved relative to
// `__filename` assuming the script lives at `packages/server/scripts/audit-migrations.ts`.
// If the script is moved into `packages/server/src/`, the paths will silently land
// one level higher. Assert the expected path at startup so a mislocated install
// fails loudly rather than silently writing to the wrong docs location.
if (!__filename.endsWith(`${sep}packages${sep}server${sep}scripts${sep}audit-migrations.ts`)) {
  logger.error("[audit-migrations] Script location unexpected", { path: __filename, expected: "packages/server/scripts/audit-migrations.ts" });
  process.exit(1);
}

/**
 * Walk the migrations directory and return one MigrationRow per `migration.sql` file,
 * sorted chronologically (ascending by directory name — which is `<timestamp>_<slug>`).
 */
function collectMigrations(): MigrationRow[] {
  let dirents;
  try {
    dirents = readdirSync(MIGRATIONS_DIR, { withFileTypes: true, recursive: true });
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      logger.error("[audit-migrations] Migrations directory not found", { dir: MIGRATIONS_DIR });
      process.exit(1);
    }
    throw err;
  }
  return dirents
    .filter((dirent) => dirent.name === "migration.sql")
    .map((dirent) => {
      // Node 24 exposes `parentPath` on Dirent when read with recursive: true.
      const parentDir = (dirent as { parentPath?: string }).parentPath ?? "";
      const sqlPath = join(parentDir, dirent.name);
      const dirName = basename(dirname(sqlPath));
      const date = formatDateFromSlug(dirName);
      return { slug: dirName, date, path: sqlPath };
    })
    .sort((a, b) => a.slug.localeCompare(b.slug));
}

function formatDateFromSlug(slug: string): string {
  // Slug starts with `YYYYMMDD` (e.g. 20260516134634_add_missing_models).
  const ts = slug.slice(0, 8);
  return /^\d{8}$/.test(ts)
    ? `${ts.slice(0, 4)}-${ts.slice(4, 6)}-${ts.slice(6, 8)}`
    : ts;
}

function buildMarkdownReport(
  rows: Array<MigrationRow & Classification>,
  additiveCount: number,
  destructiveCount: number,
): string {
  const lines: string[] = [];
  lines.push("## Migration Audit Report");
  lines.push("");
  lines.push(
    `**Total:** ${rows.length} migrations · **Additive:** ${additiveCount} · **Destructive:** ${destructiveCount}`,
  );
  lines.push("");
  lines.push("| Migration | Date | Type | Operations |");
  lines.push("|-----------|------|------|------------|");
  for (const row of rows) {
    const operations = row.type === "additive" ? "none" : row.operations.join(", ");
    const cell = (s: string) => s.replace(/\|/g, "\\|");
    lines.push(`| ${cell(row.slug)} | ${cell(row.date)} | ${cell(row.type)} | ${cell(operations)} |`);
  }
  lines.push("");
  return lines.join("\n");
}

interface AuditResult {
  generated_at: string;
  total_migrations: number;
  destructive_count: number;
  additive_count: number;
  destructive_migrations: string[];
}

function buildJsonReport(
  rows: Array<MigrationRow & Classification>,
  additiveCount: number,
  destructiveCount: number,
): AuditResult {
  return {
    generated_at: new Date().toISOString(),
    total_migrations: rows.length,
    destructive_count: destructiveCount,
    additive_count: additiveCount,
    destructive_migrations: rows.filter((r) => r.type === "destructive").map((r) => r.slug),
  };
}

function main(): void {
  const migrations = collectMigrations();
  const rows = migrations.map((m) => {
    const content = readFileSync(m.path, "utf8");
    return { ...m, ...classifyMigration(content) };
  });
  const destructiveCount = rows.filter((r) => r.type === "destructive").length;
  const additiveCount = rows.length - destructiveCount;

  writeFileSync(AUDIT_MD_PATH, buildMarkdownReport(rows, additiveCount, destructiveCount));
  writeFileSync(
    AUDIT_JSON_PATH,
    JSON.stringify(buildJsonReport(rows, additiveCount, destructiveCount), null, 2) + "\n",
  );

  console.log(
    `[audit-migrations] Scanned ${rows.length} migrations: ${additiveCount} additive, ${destructiveCount} destructive.`,
  );
}

if (require.main === module) {
  main();
  process.exit(0);
}
